#!/bin/bash
# ═══════════════════════════════════════════════════════════════
# 🚀 DEPLOY TO HUGGING FACE SPACES - FINAL COMMAND
# ═══════════════════════════════════════════════════════════════

echo ""
echo "╔═══════════════════════════════════════════════════════════════╗"
echo "║         🚀 HUGGING FACE SPACES DEPLOYMENT                     ║"
echo "║      AI Research Assistant - OpenEnv Edition                  ║"
echo "╚═══════════════════════════════════════════════════════════════╝"
echo ""

echo "Your Space: https://huggingface.co/spaces/nachikethshetty/ai-research-assistant-openenv"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "STEP 1: Get Your HF Token"
echo "────────────────────────"
echo "  1. Go to: https://huggingface.co/settings/tokens"
echo "  2. Click 'New Token'"
echo "  3. Set 'Read + Write' access"
echo "  4. Copy the token"
echo ""
echo "STEP 2: Run This Command"
echo "────────────────────────"
echo "  cd /Users/amshumathshetty/Desktop/ai-research-assistant"
echo "  git push hf main"
echo ""
echo "STEP 3: Paste Your Token"
echo "─────────────────────────"
echo "  When asked for credentials, paste your HF token"
echo "  (No need to enter username/password)"
echo ""
echo "STEP 4: Wait for Build"
echo "───────────────────────"
echo "  HF will build for 2-5 minutes"
echo "  Visit your Space URL above when ready!"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✅ Everything is configured and ready!"
echo "📦 LLM Backends: Ollama + Google Gemini (fallback)"
echo "🔄 Paper Sources: arXiv + Semantic Scholar + OpenAlex"
echo "🚀 Status: Ready to push"
echo ""
echo "Press Enter to continue, or Ctrl+C to exit..."
read

cd /Users/amshumathshetty/Desktop/ai-research-assistant
git push hf main

if [ $? -eq 0 ]; then
    echo ""
    echo "╔═══════════════════════════════════════════════════════════════╗"
    echo "║                   ✅ DEPLOYMENT SUCCESSFUL! ✅                 ║"
    echo "╚═══════════════════════════════════════════════════════════════╝"
    echo ""
    echo "🎉 Your app is deployed to HF Spaces!"
    echo ""
    echo "📍 Your Live URL:"
    echo "   https://huggingface.co/spaces/nachikethshetty/ai-research-assistant-openenv"
    echo ""
    echo "⏳ Build time: 2-5 minutes (refresh HF page to check status)"
    echo ""
    echo "💡 Next Steps:"
    echo "   • Wait for HF to build and run"
    echo "   • Click 'Running' badge → Opens live app"
    echo "   • Share URL with judges/teammates"
    echo "   • If Ollama slow, add GOOGLE_API_KEY to Space secrets"
    echo ""
    echo "📖 For full details, see:"
    echo "   HF_SPACES_DEPLOYMENT.md"
    echo "   DEPLOYMENT_READY.md"
    echo ""
else
    echo ""
    echo "❌ Deployment failed!"
    echo ""
    echo "🔧 Troubleshooting:"
    echo "   • Check your HF token is valid"
    echo "   • Get a new one: https://huggingface.co/settings/tokens"
    echo "   • Make sure you have 'Write' access enabled"
    echo "   • Try again with: git push hf main"
    echo ""
fi
